/**
 * Conteúdo verbatim extraído de docs/legal/source/03_Politica_de_Cookies_v2_0.docx.
 * Cada item é um parágrafo/linha do documento original, na ordem original.
 * NÃO editar o texto — qualquer correção pertence ao arquivo fonte (.docx), não aqui.
 * Regenerado por scripts internos de extração — ver docs/audits/2026-09-08-legal-source-of-truth.md.
 */

export const PARAGRAFOS_COOKIES: readonly string[] = [
  "POLÍTICA DE COOKIES",
  "Promofy — Plataforma Digital de Promoções e Cupons",
  "Versão 2.0  ·  Última atualização: [DATA DE PUBLICAÇÃO]",
  "Esta Política de Cookies explica o que são cookies, como a PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.), CNPJ 68.003.330/0001-74 (\"Promofy\") os utiliza, os tipos empregados e como você pode gerenciar suas preferências. Aplica-se ao site, ao aplicativo móvel e ao painel web da plataforma Promofy.",
  "1. O QUE SÃO COOKIES?",
  "Cookies são pequenos arquivos de texto ou tecnologias similares (como pixels, local storage e identificadores de sessão) armazenados no seu dispositivo quando você acessa um site ou aplicativo. Eles permitem reconhecer o dispositivo, lembrar preferências e otimizar a experiência de uso.",
  "2. POR QUE UTILIZAMOS COOKIES?",
  "Garantir o funcionamento adequado do site, app e painel web;",
  "Armazenar preferências e configurações do usuário entre sessões;",
  "Entender como os usuários interagem com a plataforma, inclusive no uso de cupons, promoções e recomendações;",
  "Realizar análises estatísticas e de desempenho para melhoria contínua;",
  "Oferecer experiência personalizada, sugerindo cupons e promoções alinhados ao perfil do usuário;",
  "Exibir campanhas publicitárias relevantes e remarketing, sempre mediante consentimento prévio;",
  "Melhorar a segurança da plataforma, prevenindo fraudes em tokens promocionais e acessos indevidos.",
  "3. TIPOS DE COOKIES QUE UTILIZAMOS",
  "Tipo",
  "Finalidade",
  "Base legal (LGPD)",
  "Cookies Necessários",
  "Login seguro, resgate de cupons, navegação básica — sem eles a plataforma não funciona",
  "Legítimo interesse",
  "Cookies de Desempenho",
  "Dados anônimos sobre uso da plataforma para otimização de funcionalidades",
  "Consentimento",
  "Cookies de Funcionalidade",
  "Preferências de idioma, região, cupons salvos e login persistente",
  "Consentimento",
  "Cookies de Publicidade",
  "Campanhas e remarketing com base no perfil e histórico de interações",
  "Consentimento",
  "Cookies de Terceiros",
  "Parceiros de analytics (Google Analytics) e publicidade (Meta Ads) — cookies instalados por esses parceiros",
  "Consentimento",
  "4. GERENCIAMENTO DE COOKIES",
  "Você pode gerenciar suas permissões de cookies diretamente nas configurações do navegador ou nas preferências do aplicativo Promofy;",
  "A Promofy disponibiliza um painel de consentimento granular, permitindo aceitar apenas categorias específicas de cookies (ex.: somente necessários + funcionais);",
  "O bloqueio de cookies necessários pode comprometer a funcionalidade da plataforma;",
  "A revogação do consentimento para cookies opcionais pode ser feita a qualquer momento sem prejuízo ao acesso aos serviços contratados.",
  "5. BASE LEGAL PARA O USO DE COOKIES",
  "Consentimento (LGPD, art. 7º, I): cookies de análise, publicidade, remarketing e personalização — solicitados no momento do primeiro acesso.",
  "Legítimo interesse (LGPD, art. 7º, IX): cookies necessários e de segurança, essenciais ao funcionamento da plataforma.",
  "6. DIREITOS DO TITULAR",
  "Revogar ou modificar o consentimento dado a qualquer momento;",
  "Solicitar informações sobre os cookies utilizados e os dados coletados;",
  "Exercer os direitos de acesso, correção, anonimização ou eliminação conforme a LGPD.",
  "Contato: privacidade@usepromofy.com",
  "7. ALTERAÇÕES NESTA POLÍTICA",
  "Esta Política pode ser atualizada periodicamente. Mudanças relevantes serão comunicadas nos canais oficiais da Promofy (app, site ou e-mail) com antecedência mínima de 10 dias.",
  "8. CONTATO",
  "Em caso de dúvidas: privacidade@usepromofy.com Entre em contato: contato@usepromofy.com."
];
