/**
 * Conteúdo verbatim extraído de docs/legal/source/02_Politica_de_Privacidade_v2_0.docx.
 * Cada item é um parágrafo/linha do documento original, na ordem original.
 * NÃO editar o texto — qualquer correção pertence ao arquivo fonte (.docx), não aqui.
 * Regenerado por scripts internos de extração — ver docs/audits/2026-09-08-legal-source-of-truth.md.
 */

export const PARAGRAFOS_PRIVACIDADE: readonly string[] = [
  "POLÍTICA DE PRIVACIDADE",
  "Promofy — Plataforma Digital de Promoções e Cupons",
  "Versão 2.0  ·  Última atualização: [DATA DE PUBLICAÇÃO]",
  "A PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.), inscrita no CNPJ sob o nº 68.003.330/0001-74, com sede na Quadra ARSO 151 QI 26, nº 42B, Alameda 34, Plano Diretor Sul, Palmas – Tocantins, CEP 77.025-440, e-mail contato@usepromofy.com, CEP 77.025-440, operadora da plataforma PROMOFY (\"Promofy\"), reafirma seu compromisso com a segurança, privacidade e transparência no tratamento dos dados pessoais de usuários e estabelecimentos parceiros, em conformidade com a Lei Geral de Proteção de Dados Pessoais – LGPD (Lei nº 13.709/2018) e demais normas aplicáveis.",
  "1. DADOS COLETADOS",
  "1.1 Dados de cadastro do usuário consumidor:",
  "Nome completo, CPF, data de nascimento e RG (quando aplicável);",
  "Endereço de e-mail e número de telefone celular;",
  "Dados de pagamento (processados de forma criptografada pelo gateway de pagamento — a Promofy não armazena dados de cartão);",
  "Dados do dispositivo de acesso (modelo, sistema operacional, identificador único).",
  "1.2 Dados de cadastro do estabelecimento parceiro:",
  "Razão social, CNPJ e nome fantasia;",
  "Endereço completo e dados de geolocalização do estabelecimento;",
  "Dados do representante legal: nome, CPF, cargo, telefone e e-mail;",
  "Informações de ofertas, promoções e cupons cadastrados na plataforma.",
  "1.3 Dados coletados automaticamente:",
  "Endereço IP e identificadores de sessão;",
  "Cookies e tecnologias similares (conforme Política de Cookies);",
  "Localização geográfica, quando expressamente autorizada pelo usuário;",
  "Interações no app: resgates de cupons, tempo de uso, pesquisas, preferências de consumo, histórico de ativações.",
  "1.4 Dados de terceiros:",
  "Informações de usuários indicados, somente com consentimento do titular (nome e e-mail para o fluxo de indicação);",
  "Feedback de estabelecimentos sobre usuários, tratados de forma anonimizada para fins estatísticos.",
  "2. FINALIDADES DO TRATAMENTO",
  "Os dados pessoais são utilizados para as seguintes finalidades, conforme base legal indicada:",
  "Finalidade",
  "Base legal (LGPD, art. 7º)",
  "Gestão de conta e autenticação",
  "Execução de contrato (inc. V)",
  "Exibição de cupons e promoções personalizadas",
  "Legítimo interesse (inc. IX)",
  "Controle de planos, assinaturas e pagamentos",
  "Execução de contrato (inc. V)",
  "Sugestões por IA e recomendação personalizada",
  "Consentimento (inc. I)",
  "Prevenção de fraudes e segurança da plataforma",
  "Legítimo interesse (inc. IX)",
  "Comunicações de marketing e novidades",
  "Consentimento (inc. I)",
  "Cumprimento de obrigações legais e regulatórias",
  "Obrigação legal (inc. II)",
  "NPS, feedbacks e melhoria dos serviços",
  "Legítimo interesse (inc. IX)",
  "Exportação de CRM para estabelecimentos parceiros",
  "Execução de contrato (inc. V)",
  "3. COMPARTILHAMENTO DE DADOS",
  "A Promofy não comercializa dados pessoais. O compartilhamento poderá ocorrer:",
  "Com estabelecimentos parceiros, somente os dados estritamente necessários para validação de cupons e geração de CRM (nome, e-mail, telefone, data de nascimento e histórico de cupons no estabelecimento);",
  "Com provedores de tecnologia e infraestrutura (Supabase, Google Cloud Platform) vinculados por acordos de processamento de dados compatíveis com a LGPD;",
  "Com gateway de pagamento (Mercado Pago) para processamento de transações financeiras;",
  "Com autoridades públicas, em cumprimento a ordens judiciais ou obrigações legais.",
  "4. DIREITOS DO TITULAR",
  "O usuário e o estabelecimento parceiro têm direito a, a qualquer momento:",
  "Confirmar a existência de tratamento de seus dados pessoais;",
  "Solicitar acesso, correção ou atualização de dados incorretos ou desatualizados;",
  "Solicitar anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade com a LGPD;",
  "Revogar o consentimento para finalidades baseadas nessa base legal;",
  "Solicitar portabilidade dos dados, quando tecnicamente viável;",
  "Solicitar informações sobre compartilhamento com terceiros;",
  "Opor-se ao tratamento realizado com base em legítimo interesse.",
  "Pedidos devem ser encaminhados para: privacidade@usepromofy.com",
  "5. SEGURANÇA DA INFORMAÇÃO",
  "Criptografia de dados sensíveis em repouso e em trânsito (TLS 1.2+);",
  "Controle de acesso com perfil e autenticação de múltiplos fatores (MFA) para ambientes de produção;",
  "Logs de auditoria com retenção mínima de 12 meses;",
  "Backups criptografados com frequência diária;",
  "Política interna de acesso mínimo (least privilege);",
  "Monitoramento contínuo de incidentes e notificação da CONTRATANTE em até 24h de incidentes de segurança relevantes.",
  "6. RETENÇÃO E EXCLUSÃO DE DADOS",
  "Os dados são mantidos enquanto houver vínculo ativo com a plataforma;",
  "Após o encerramento da conta, os dados pessoais serão anonimizados para fins estatísticos no prazo de 30 dias, salvo obrigação legal de retenção;",
  "Dados necessários ao cumprimento de obrigações legais, fiscais ou regulatórias serão mantidos pelo prazo exigido em lei (ex.: dados fiscais por 5 anos, conforme Código Tributário Nacional);",
  "O usuário pode solicitar a exclusão antecipada de sua conta e dados a qualquer momento, com efetivação em até 30 dias.",
  "7. ENCARREGADO DE DADOS (DPO)",
  "O Encarregado de Proteção de Dados (DPO) da Promofy é responsável por receber comunicações dos titulares e da Autoridade Nacional de Proteção de Dados (ANPD). Contato: privacidade@usepromofy.com",
  "8. ALTERAÇÕES NESTA POLÍTICA",
  "A Promofy poderá atualizar esta Política a qualquer tempo. Alterações relevantes serão comunicadas por notificação no app, no site ou por e-mail com antecedência mínima de 10 dias antes da entrada em vigor da nova versão.",
  "9. DISPOSIÇÕES FINAIS",
  "O uso da Promofy implica aceite integral desta Política de Privacidade;",
  "Casos omissos serão resolvidos conforme a LGPD e a legislação brasileira aplicável;",
  "Foro eleito: comarca de Palmas – Tocantins."
];
