/**
 * Conteúdo verbatim extraído de docs/legal/source/Termo_Gamificacao_PromoPoints_Promofy.docx.
 * Cada item é um parágrafo/linha do documento original, na ordem original.
 * NÃO editar o texto — qualquer correção pertence ao arquivo fonte (.docx), não aqui.
 * Regenerado por scripts internos de extração — ver docs/audits/2026-09-08-legal-source-of-truth.md.
 */

export const PARAGRAFOS_PROMOPOINTS: readonly string[] = [
  "PROMOFY",
  "Promoção na palma da mão!",
  "TERMO DE PARTICIPAÇÃO NO",
  "PROGRAMA DE GAMIFICAÇÃO",
  "Sistema PromoPoints",
  "Versão 1.0",
  "PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.)",
  "Sumário",
  "TOC \\h \\o \"1-2\"",
  "1. Preâmbulo e Aceitação",
  "Este Termo de Participação no Programa de Gamificação (“Termo”) regula o sistema de pontos denominado PromoPoints, oferecido pela PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.), inscrita no CNPJ sob o nº 68.003.330/0001-74, titular da plataforma Promofy (“Promofy”, “nós” ou “plataforma”), aos usuários consumidores da plataforma (“Usuário”, “Você” ou “Participante”), e-mail para contato: contato@usepromofy.com.",
  "1.1  A participação no Programa de Gamificação é voluntária e gratuita, e está condicionada à aceitação integral deste Termo, bem como dos Termos de Uso e da Política de Privacidade da Promofy, dos quais este documento é parte complementar e integrante.",
  "1.2  Ao marcar a opção de aceite, ao acumular ou resgatar PromoPoints, ou ao praticar qualquer ação pontuável descrita neste Termo, o Usuário declara que leu, compreendeu e concorda integralmente com todas as suas cláusulas.",
  "1.3  Caso o Usuário não concorde com qualquer disposição deste Termo, não deverá participar do Programa de Gamificação. A não participação no Programa não impede o uso das demais funcionalidades da Promofy conforme os Termos de Uso aplicáveis.",
  "LEIA COM ATENÇÃO",
  "Este Termo descreve como ganhar PromoPoints, o que é permitido e o que é proibido, e as consequências de condutas irregulares, que incluem o estorno de pontos, a suspensão e o banimento da conta. Leia com atenção, especialmente as Seções 6, 7 e 8.",
  "2. Definições",
  "Para os fins deste Termo, aplicam-se as seguintes definições:",
  "PromoPoints (ou “Pontos”): unidade virtual de pontuação do Programa de Gamificação, sem valor monetário, não conversível em dinheiro e intransferível, utilizada exclusivamente dentro da plataforma Promofy conforme este Termo.",
  "Programa de Gamificação: o conjunto de regras, ações pontuáveis, rankings e recompensas que compõem o sistema PromoPoints.",
  "Ação Pontuável: qualquer atividade do Usuário que gere crédito de PromoPoints, conforme a Seção 4.",
  "Ranking: a classificação dos Usuários por pontuação acumulada, apurada periodicamente.",
  "Recompensa: benefício que pode ser obtido mediante resgate de PromoPoints, conforme disponibilidade definida pela Promofy.",
  "Consumo de Cupom com baixa confirmada: o ato de utilizar um cupom no estabelecimento parceiro, confirmado por este dentro do prazo de validade do código, gerando o registro válido da transação.",
  "Resgatado sem baixa: status do cupom cujo código foi gerado mas não confirmado pelo estabelecimento dentro do prazo; não gera PromoPoints.",
  "Conduta Fraudulenta: qualquer ação destinada a obter PromoPoints de forma indevida, contornando as regras deste Termo, conforme detalhado na Seção 6.",
  "3. Elegibilidade e Participação",
  "3.1  Pode participar do Programa de Gamificação o Usuário pessoa física, maior de 18 anos, com cadastro ativo e regular na Promofy, com CPF válido e verificado.",
  "3.2  Cada Usuário pode manter apenas uma (1) conta na Promofy. É vedada a criação ou manutenção de múltiplas contas pela mesma pessoa, ainda que com dados parcialmente distintos.",
  "3.3  Os PromoPoints são pessoais e intransferíveis, vinculados ao CPF do Usuário titular da conta. Não podem ser cedidos, vendidos, doados, combinados entre contas ou transferidos a terceiros, a qualquer título.",
  "3.4  Os PromoPoints não possuem valor monetário, não constituem moeda, crédito, título ou ativo financeiro, e não são conversíveis ou resgatáveis em dinheiro, em espécie ou por transferência (incluindo PIX), em nenhuma hipótese.",
  "4. Ações Pontuáveis e Regras de Crédito",
  "As ações que geram PromoPoints, seus valores e limites são os descritos na tabela abaixo, podendo ser revistos conforme a Seção 9.",
  "Ação do Usuário",
  "Pontos",
  "Frequência máxima",
  "Quando é creditado",
  "Consumir cupom (com baixa confirmada)",
  "100",
  "Sem limite",
  "Após confirmação do resgate pelo estabelecimento",
  "Avaliar (responder NPS)",
  "50",
  "1x por cupom",
  "Após o envio da avaliação de um cupom com baixa",
  "Indicar amigo que assina plano",
  "200",
  "5x por mês",
  "Após a assinatura paga do indicado e o decurso do prazo de arrependimento",
  "Primeiro acesso",
  "50",
  "Única vez",
  "No primeiro login após o download",
  "Check-in diário",
  "5",
  "1x por dia",
  "Ao abrir o app no dia",
  "4.1 Regras específicas de cada ação",
  "4.1.1  Consumo de cupom.",
  "Os 100 PromoPoints são creditados exclusivamente quando o consumo do cupom é confirmado pelo estabelecimento parceiro (“baixa”) dentro do prazo de validade do código. Cupons com status “Resgatado sem baixa” — isto é, cujo código foi gerado mas não confirmado pelo estabelecimento — não geram PromoPoints, ainda que contem contra o limite mensal de cupons do plano do Usuário.",
  "4.1.2  Avaliação (NPS).",
  "Os 50 PromoPoints por avaliação são creditados uma única vez por cupom efetivamente consumido com baixa confirmada, mediante resposta à pesquisa de satisfação. Avaliações de cupons sem baixa não são pontuadas.",
  "4.1.3  Indicação de amigo.",
  "Os 200 PromoPoints por indicação são creditados somente quando o Usuário indicado, por meio do link ou código de indicação do Participante, efetivamente assina um plano pago da Promofy e decorre o prazo de arrependimento de 7 (sete) dias previsto no art. 49 do Código de Defesa do Consumidor, sem cancelamento. O simples cadastro do indicado, sem assinatura de plano pago, não gera pontos. A pontuação por indicação está limitada a 5 (cinco) indicações pontuadas por mês.",
  "Para que a indicação seja válida, o indicado deve ser pessoa distinta do indicador, com CPF próprio e distinto, utilizando dispositivo e meio de pagamento distintos dos do indicador. Indicações que não atendam a esses critérios não serão pontuadas e poderão caracterizar Conduta Fraudulenta.",
  "4.1.4  Primeiro acesso e check-in diário.",
  "O bônus de primeiro acesso é creditado uma única vez por conta. O check-in diário é creditado uma vez a cada dia civil em que o Usuário acessa o aplicativo, não sendo cumulativo nem retroativo.",
  "4.2 Condições gerais de crédito",
  "4.2.1  Os PromoPoints somente são creditados após a confirmação da ação pontuável correspondente. Ações pendentes, não confirmadas ou canceladas não geram crédito.",
  "4.2.2  A Promofy poderá reter a apuração ou o crédito de PromoPoints pelo tempo necessário à verificação da regularidade da ação, especialmente em casos de suspeita de Conduta Fraudulenta.",
  "4.2.3  Caso uma ação que gerou pontos seja posteriormente revertida, cancelada ou identificada como irregular (por exemplo, cancelamento de assinatura de indicado dentro do prazo de arrependimento, estorno de pagamento ou chargeback), os PromoPoints correspondentes serão estornados, podendo a conta ficar com saldo negativo até a devida compensação.",
  "5. Ranking, Recompensas e Validade",
  "5.1  Os PromoPoints posicionam o Usuário em um Ranking periódico, cujos critérios, periodicidade e eventuais premiações são divulgados pela Promofy no aplicativo.",
  "5.2  As Recompensas disponíveis para resgate, sua quantidade de pontos exigida e sua disponibilidade são definidas exclusivamente pela Promofy e podem ser alteradas, incluídas ou descontinuadas a qualquer tempo, sem que isso gere direito adquirido ou obrigação de manutenção.",
  "5.3  As Recompensas consistem em benefícios dentro do ecossistema da Promofy (tais como cupons especiais, descontos na assinatura, upgrades de plano ou pacotes de cupons), nunca em dinheiro. A Promofy não paga, em nenhuma hipótese, valores em espécie, transferência ou PIX a título de PromoPoints.",
  "5.4  Validade dos pontos.",
  "Os PromoPoints poderão ter prazo de validade, a ser informado no aplicativo. Pontos não utilizados dentro do prazo de validade expiram automaticamente, sem direito a reposição ou compensação.",
  "5.5  A pontuação e o saldo de PromoPoints estão vinculados à manutenção de conta ativa e regular. O encerramento da conta, por iniciativa do Usuário ou da Promofy, implica a perda do saldo de PromoPoints, ressalvado o disposto na Seção 8.",
  "6. Condutas Proibidas e Fraude",
  "Constitui Conduta Fraudulenta, sujeita às penalidades da Seção 7, a prática, tentativa ou facilitação de qualquer das ações abaixo, de forma exemplificativa e não exaustiva:",
  "6.1 Manipulação de contas e identidade",
  "Criar, manter ou utilizar mais de uma conta na Promofy, próprias ou de terceiros, para acumular ou multiplicar PromoPoints.",
  "Criar contas falsas, fictícias, com dados de terceiros, com dados inventados ou em nome de pessoas sem o seu consentimento.",
  "Realizar autoindicação, indicação cruzada combinada ou indicações entre contas controladas pela mesma pessoa ou grupo coordenado, com o fim de obter pontos de indicação.",
  "Utilizar CPF, dispositivo, número de telefone ou meio de pagamento de terceiros para simular indicados ou ações distintas.",
  "6.2 Manipulação de ações pontuáveis",
  "Simular consumos de cupons que não correspondem a uma intenção real de uso no estabelecimento.",
  "Combinar-se com estabelecimentos para registrar baixas de cupons sem o consumo correspondente, com o fim de gerar pontos.",
  "Responder avaliações (NPS) de forma automatizada, repetitiva ou desvinculada de um consumo real.",
  "Realizar check-ins ou quaisquer ações por meio de automação, scripts, bots, emuladores ou ferramentas que simulem a atividade humana.",
  "6.3 Manipulação técnica",
  "Explorar falhas, brechas, erros (bugs) ou comportamentos inesperados da plataforma para obter pontos indevidos.",
  "Utilizar engenharia reversa, interceptação de requisições, manipulação de aplicativo ou qualquer meio técnico para alterar a contagem de pontos.",
  "Burlar, desativar ou contornar os mecanismos de segurança, validação de identidade ou detecção de fraude da Promofy (incluindo verificação de CPF e identificação de dispositivo).",
  "Comercializar, anunciar, transferir ou tentar transferir PromoPoints, contas ou indicações a terceiros, a qualquer título.",
  "DETECÇÃO E BOA-FÉ",
  "A Promofy utiliza mecanismos automatizados e manuais de detecção de fraude, incluindo verificação de CPF e identificação de dispositivo.",
  "A ausência de menção a uma conduta específica neste Termo não a torna permitida: qualquer ação que viole a boa-fé, contorne as regras ou distorça o propósito do Programa poderá ser tratada como Conduta Fraudulenta.",
  "7. Penalidades",
  "Identificada Conduta Fraudulenta ou violação a este Termo, a Promofy poderá aplicar, isolada ou cumulativamente, conforme a gravidade, as seguintes medidas, a seu critério:",
  "7.1  Estorno de pontos.",
  "Cancelamento e estorno dos PromoPoints obtidos de forma irregular, podendo a conta ficar com saldo negativo. Recompensas resgatadas com pontos irregulares poderão ser canceladas.",
  "7.2  Advertência.",
  "Notificação ao Usuário sobre a irregularidade identificada, com possibilidade de regularização quando aplicável.",
  "7.3  Suspensão.",
  "Suspensão temporária da participação no Programa de Gamificação e/ou do acesso à conta, pelo período necessário à apuração ou como sanção, durante o qual o Usuário não acumula nem resgata PromoPoints.",
  "7.4  Exclusão do Programa.",
  "Exclusão definitiva do Usuário do Programa de Gamificação, com perda integral do saldo de PromoPoints, mantida (a critério da Promofy) a conta para uso das demais funcionalidades.",
  "7.5  Banimento.",
  "Encerramento definitivo da conta e banimento do Usuário da plataforma Promofy, com perda integral dos PromoPoints, nos casos de fraude grave, reincidência ou má-fé qualificada. O banimento pode impedir a criação de nova conta pela mesma pessoa.",
  "7.6 Critérios de gradação",
  "A escolha da penalidade considera a gravidade, a reincidência, a extensão do dano, a intenção (boa ou má-fé) e o histórico do Usuário. Condutas isoladas e de menor potencial poderão ensejar apenas estorno e advertência; fraudes estruturadas, reincidentes ou de má-fé ensejam suspensão, exclusão ou banimento.",
  "BANIMENTO IMEDIATO",
  "Casos que tipicamente ensejam banimento imediato:",
  "Operação de redes de contas falsas; conluio com estabelecimentos para baixas fictícias; comercialização de pontos ou contas; uso de automação em escala; e reincidência após suspensão ou exclusão anterior.",
  "7.7  As penalidades deste Termo são independentes e não excluem as medidas previstas nos Termos de Uso da Promofy, nem eventuais providências cíveis e criminais cabíveis em razão da conduta.",
  "7.8  A aplicação de penalidade relativa ao Programa de Gamificação não gera direito a indenização, reembolso de assinatura ou compensação ao Usuário pelos PromoPoints perdidos, dado o caráter gratuito e sem valor monetário dos Pontos.",
  "8. Apuração, Contraditório e Boa-fé da Promofy",
  "8.1  Antes da aplicação de penalidades mais gravosas (exclusão ou banimento) por Conduta Fraudulenta, a Promofy buscará, sempre que possível e quando não comprometer a segurança da plataforma ou de terceiros, dar ao Usuário a oportunidade de se manifestar sobre os fatos.",
  "8.2  Em situações de risco evidente, fraude em andamento ou ameaça à integridade da plataforma e dos demais usuários, a Promofy poderá aplicar medidas cautelares imediatas (como suspensão preventiva), assegurando a manifestação posterior do Usuário.",
  "8.3  O Usuário poderá contestar a medida aplicada por meio dos canais de atendimento da Promofy, apresentando informações e esclarecimentos, que serão analisados de boa-fé.",
  "8.4  As decisões sobre concessão, estorno de pontos e aplicação de penalidades são tomadas pela Promofy com base em seus mecanismos de verificação; a Promofy compromete-se a agir de boa-fé, de forma proporcional e não discriminatória.",
  "9. Alterações e Disposições Gerais",
  "9.1  A Promofy poderá alterar este Termo, as ações pontuáveis, os valores de pontos, os limites, as recompensas e as regras do Programa a qualquer tempo, mediante publicação da versão atualizada no aplicativo, com indicação da data de vigência.",
  "9.2  Alterações não reduzem retroativamente os PromoPoints já validamente acumulados, salvo nos casos de estorno por irregularidade previstos neste Termo. O uso continuado do Programa após a vigência das alterações implica concordância com a nova versão.",
  "9.3  A Promofy poderá suspender, descontinuar ou encerrar o Programa de Gamificação a qualquer tempo, mediante aviso prévio razoável no aplicativo, sem que isso gere direito a indenização, dado o caráter gratuito e promocional do Programa e a inexistência de valor monetário dos PromoPoints.",
  "9.4  A tolerância da Promofy quanto a eventual descumprimento deste Termo não constitui novação nem renúncia ao direito de exigir seu cumprimento ou de aplicar as penalidades cabíveis.",
  "9.5  Este Termo é regido pelas leis da República Federativa do Brasil. Fica eleito o foro da Comarca de Palmas – Tocantins para dirimir controvérsias, sem prejuízo da competência do foro do domicílio do consumidor, nos termos da legislação aplicável, CEP 77.025-440.",
  "10. Declaração de Aceite",
  "Ao aceitar este Termo, o Usuário declara que:",
  "Leu e compreendeu integralmente este Termo de Participação no Programa de Gamificação;",
  "Concorda em participar do Programa de acordo com as regras aqui estabelecidas;",
  "Compreende que os PromoPoints não possuem valor monetário e não são conversíveis em dinheiro;",
  "Está ciente das condutas proibidas e das penalidades aplicáveis, incluindo estorno de pontos, suspensão e banimento;",
  "Compromete-se a participar de boa-fé, sem recorrer a fraude, automação ou múltiplas contas.",
  "A aceitação eletrônica deste Termo, mediante marcação da opção correspondente no aplicativo, tem plena validade jurídica e vincula o Usuário a todas as suas disposições.",
  "Promofy — Termo de Participação no Programa de Gamificação (PromoPoints) — v1.0",
  "PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.)"
];
