/**
 * Conteúdo verbatim extraído de docs/legal/source/05_Termos_de_Uso_Parceiros_v3_0.docx.
 * Cada item é um parágrafo/linha do documento original, na ordem original.
 * NÃO editar o texto — qualquer correção pertence ao arquivo fonte (.docx), não aqui.
 * Regenerado por scripts internos de extração — ver docs/audits/2026-09-08-legal-source-of-truth.md.
 */

export const PARAGRAFOS_TERMOS_PARCEIRO: readonly string[] = [
  "TERMO DE USO — ESTABELECIMENTOS PARCEIROS",
  "Plataforma Promofy — Gestão de Cupons e Promoções",
  "Versão 3.0  ·  Última atualização: [DATA DE PUBLICAÇÃO]",
  "Ao aderir à plataforma Promofy, o estabelecimento declara ter lido, compreendido e aceito integralmente este Termo de Uso. A adesão é condição essencial para utilização dos serviços.",
  "1. IDENTIFICAÇÃO DAS PARTES",
  "Promofy (Plataforma)",
  "PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.) — 68.003.330/0001-74 | Nome Fantasia: Promofy | Palmas – Tocantins",
  "Parceiro",
  "Estabelecimento comercial que adere à plataforma mediante aceite eletrônico deste Termo",
  "2. OBJETO",
  "Este Termo regula a adesão, permanência e utilização da plataforma Promofy por estabelecimentos comerciais parceiros, estabelecendo direitos e obrigações mútuos. A Promofy atua como intermediadora tecnológica entre consumidores e estabelecimentos, oferecendo ambiente digital para divulgação, distribuição e gestão de cupons e promoções.",
  "3. NATUREZA DA RELAÇÃO",
  "A Promofy NÃO é fornecedora dos produtos ou serviços ofertados pelos parceiros;",
  "A responsabilidade integral pela execução, qualidade, prazos, atendimento e cumprimento das ofertas é exclusiva do parceiro;",
  "Eventuais reclamações, demandas judiciais ou extrajudiciais relacionadas às ofertas são de inteira responsabilidade do parceiro, isentando a Promofy de qualquer corresponsabilidade perante consumidores;",
  "Não há vínculo empregatício, societário ou de representação entre a Promofy e o parceiro.",
  "4. CADASTRO E VALIDAÇÃO",
  "O cadastro exige: razão social/CNPJ ou nome/CPF, endereço, dados do representante legal (nome, CPF, cargo, e-mail, telefone) e logotipo;",
  "Durante a fase de tração, todos os cadastros são revisados e aprovados manualmente pela Promofy antes da ativação;",
  "O parceiro receberá e-mail de confirmação após aprovação;",
  "O parceiro compromete-se a manter seus dados cadastrais sempre atualizados.",
  "5. GESTÃO DE CUPONS",
  "O parceiro pode criar cupons com: título, benefício, desconto, validade, dias e horários de uso, formato de consumo (no local, retirada ou delivery), limite de usos por usuário e imagem;",
  "Não há limite de cupons ativos por estabelecimento;",
  "Cupons são submetidos à revisão manual da Promofy antes da publicação, durante a fase de tração;",
  "O sistema exibe aviso automático quando o desconto cadastrado está abaixo do piso de visibilidade do plano gratuito — calculado dinamicamente com base no preço do plano Básico vigente;",
  "O parceiro pode ativar, pausar, reativar e editar cupons pelo painel web ou pelo app do estabelecimento.",
  "6. VALIDAÇÃO DE RESGATES",
  "O parceiro é responsável por confirmar o resgate dos cupons apresentados pelos consumidores no momento do atendimento;",
  "A validação pode ser feita por: leitura de QR Code, digitação do código único (PRM-XXXXXX) ou, em contingência, pelos dados pessoais do consumidor (nome + CPF);",
  "O não registro da baixa manual pelo parceiro dentro do prazo de validade do código resulta no status 'Resgatado sem baixa', com implicações para o consumidor (sem PromoPoints, sem NPS);",
  "É vedado recusar o atendimento a consumidor que apresente código válido, não expirado e dentro das regras do cupom.",
  "7. CRM E DADOS DE CLIENTES",
  "O CRM é gerado automaticamente a cada resgate confirmado: nome, e-mail, celular, data de nascimento e histórico de cupons do cliente no estabelecimento;",
  "O parceiro pode exportar o CRM em Excel (.xlsx) e PDF;",
  "Os dados do CRM devem ser tratados exclusivamente para fins de relacionamento com o cliente e nunca compartilhados com terceiros sem consentimento do titular;",
  "O parceiro, ao acessar dados pessoais dos consumidores via CRM, torna-se controlador desses dados nos termos da LGPD e assume as responsabilidades correspondentes.",
  "8. RESPONSABILIDADES DO PARCEIRO",
  "Garantir a veracidade, clareza e cumprimento integral das promoções divulgadas;",
  "Não veicular conteúdo ofensivo, ilegal, enganoso ou em desacordo com a legislação;",
  "Manter equipe apta a atender os consumidores atraídos via Promofy;",
  "Cumprir o Código de Defesa do Consumidor (Lei 8.078/1990) em todas as relações com os consumidores finais;",
  "Manter as credenciais de acesso ao painel em sigilo.",
  "9. RESPONSABILIDADES DA PROMOFY",
  "Disponibilizar a plataforma em ambiente seguro e funcional;",
  "Fornecer suporte técnico básico;",
  "Zelar pela proteção de dados conforme a LGPD;",
  "A Promofy não se responsabiliza por: não conformidade das ofertas; atos do estabelecimento; rejeição de cupons pelo parceiro; danos oriundos da relação entre parceiro e consumidor;",
  "A Promofy NÃO garante volume mínimo de clientes, vendas ou resultados financeiros.",
  "10. DIREITOS DA PROMOFY",
  "Auditar e moderar ofertas divulgadas a qualquer tempo;",
  "Suspender ou desativar estabelecimentos que descumpram este Termo;",
  "Utilizar informações comerciais do parceiro para divulgação da plataforma, respeitados os limites da confidencialidade;",
  "Utilizar dados anonimizados de desempenho para benchmarking e melhoria dos algoritmos de recomendação.",
  "11. DIREITOS DO PARCEIRO",
  "Acessar, corrigir ou excluir seus dados cadastrais a qualquer momento;",
  "Exportar o CRM dos seus clientes;",
  "Solicitar esclarecimentos pelo canal: contato@usepromofy.com;",
  "Solicitar a portabilidade dos dados, quando aplicável.",
  "12. PERMANÊNCIA E RESCISÃO",
  "12.1 Durante a fase inicial de tração, a Promofy não impõe prazo mínimo de permanência para estabelecimentos, visando reduzir barreiras de adesão e maximizar o volume de parceiros na plataforma.",
  "12.2 O parceiro que desejar se desligar voluntariamente deverá notificar a Promofy com antecedência mínima de 15 (quinze) dias, pelo canal contato@usepromofy.com.",
  "12.3 A Promofy poderá rescindir a parceria imediatamente em casos de: (a) ofertas enganosas ou descumpridas; (b) reclamações recorrentes de consumidores; (c) uso indevido da plataforma; (d) descumprimento da LGPD ou deste Termo.",
  "13. PROPRIEDADE INTELECTUAL",
  "O uso da plataforma não implica cessão de propriedade intelectual ao parceiro. É vedado reproduzir, copiar, modificar ou criar obras derivadas da estrutura, lógica, código ou identidade visual da Promofy sem autorização expressa.",
  "14. LICENÇA DE USO",
  "A Promofy concede ao parceiro uma licença de uso não exclusiva, intransferível e revogável para acessar e utilizar as funcionalidades da plataforma exclusivamente para os fins previstos neste Termo.",
  "15. ALTERAÇÕES NOS TERMOS",
  "A Promofy pode alterar este Termo mediante notificação prévia de 10 (dez) dias pelos canais oficiais. A permanência na plataforma após a notificação implica aceite da nova versão.",
  "16. DISPOSIÇÕES GERAIS",
  "Foro: comarca de Palmas – Tocantins, CEP 77.025-440, com renúncia a qualquer outro;",
  "Lei aplicável: legislação brasileira, em especial o Código Civil, o CDC, a LGPD e o Marco Civil da Internet;",
  "A tolerância não implica novação ou renúncia de direitos;",
  "Contato: contato@usepromofy.com | Privacidade: privacidade@usepromofy.com."
];
