/**
 * Conteúdo verbatim extraído de docs/legal/source/04_Termos_de_Uso_Consumidor_v2_0.docx.
 * Cada item é um parágrafo/linha do documento original, na ordem original.
 * NÃO editar o texto — qualquer correção pertence ao arquivo fonte (.docx), não aqui.
 * Regenerado por scripts internos de extração — ver docs/audits/2026-09-08-legal-source-of-truth.md.
 */

export const PARAGRAFOS_TERMOS_CONSUMIDOR: readonly string[] = [
  "TERMOS DE USO",
  "Plataforma Promofy — Usuários Consumidores",
  "Versão 2.0  ·  Última atualização: [DATA DE PUBLICAÇÃO]",
  "Ao acessar ou utilizar a plataforma Promofy (aplicativo ou website), o usuário declara ter lido, compreendido e aceito integralmente os presentes Termos de Uso. O aceite é condição essencial para utilização da plataforma.",
  "1. IDENTIFICAÇÃO DA EMPRESA",
  "Razão Social",
  "PROMOFY TECNOLOGIA INOVA SIMPLES (I.S.) — CNPJ 68.003.330/0001-74",
  "Nome Fantasia",
  "Promofy",
  "CNPJ",
  "A ser obtido no ato da abertura",
  "Sede",
  "Quadra ARSO 151, QI 26, nº 42B, Alameda 34, Plano Diretor Sul, Palmas – Tocantins, CEP 77.025-440",
  "E-mail",
  "contato@usepromofy.com",
  "DPO / Privacidade",
  "privacidade@usepromofy.com",
  "2. OBJETO",
  "A Promofy é uma plataforma digital que intermedia o acesso de usuários a cupons de desconto, promoções e benefícios oferecidos por estabelecimentos parceiros. A Promofy NÃO é fornecedora dos bens ou serviços objeto das promoções, limitando-se a disponibilizar o ambiente digital para interação entre usuários e estabelecimentos. Toda e qualquer questão relativa à execução, qualidade, disponibilidade ou conformidade dos produtos e serviços ofertados é de responsabilidade exclusiva do estabelecimento parceiro, conforme detalhado na Seção 8.",
  "3. CADASTRO E ELEGIBILIDADE",
  "O cadastro é pessoal, intransferível e restrito a pessoas físicas maiores de 18 anos ou legalmente emancipadas;",
  "São campos obrigatórios para cadastro: CPF (único por conta), e-mail, nome completo, celular, data de nascimento e senha;",
  "O CPF é utilizado como identificador único — não são permitidas contas duplicadas;",
  "O aceite dos Termos de Uso é obrigatório para finalizar o cadastro;",
  "O usuário é responsável pela veracidade, atualização e segurança das informações fornecidas;",
  "O uso de dados falsos ou de terceiros sem autorização configura infração e resultará em suspensão da conta e adoção das medidas legais cabíveis;",
  "Campo opcional de código promocional no cadastro permite ativação de plano VIP quando válido;",
  "O usuário é integralmente responsável pela guarda e sigilo de sua senha, código de acesso e demais credenciais. A Promofy não se responsabiliza por danos decorrentes do uso indevido da conta por terceiros em razão de quebra de sigilo causada pelo próprio usuário;",
  "Para fins de prevenção a fraudes, o estabelecimento parceiro poderá solicitar a apresentação de documento oficial com foto para confirmar a identidade do usuário no momento do resgate de cupons, especialmente em benefícios de maior valor.",
  "4. PLANOS DE ASSINATURA E PAGAMENTO",
  "4.1 Estrutura dos planos:",
  "Plano",
  "Preço",
  "Cupons/mês",
  "Acesso ao catálogo",
  "Observação",
  "Promo (Gratuito)",
  "—",
  "1 cupom",
  "Cupons selecionados",
  "Piso dinâmico de desconto",
  "Básico",
  "R$ 9,90/mês",
  "Até 5",
  "Cidade completa",
  "Plano anual — 12 meses",
  "Plus",
  "R$ 19,90/mês",
  "Ilimitados",
  "Cidade + região",
  "Plano anual — 12 meses",
  "Família",
  "R$ 29,90/mês",
  "Ilimitados (4 perfis)",
  "Cidade completa",
  "Plano anual — 12 meses",
  "VIP",
  "Premiação/convite",
  "Ilimitados",
  "Antecipado + exclusivos",
  "Pontuação dobrada",
  "4.2 Natureza dos planos pagos — LEIA COM ATENÇÃO:",
  "Todos os planos pagos são ANUAIS. O usuário contrata 12 meses de acesso, podendo optar por: (a) pagamento à vista do valor anual, com desconto; ou (b) parcelamento em 12 parcelas mensais.",
  "O compromisso é de 12 meses em ambas as modalidades;",
  "O cancelamento do plano não interrompe a obrigação de pagamento das parcelas restantes até o término dos 12 meses contratados — o acesso é mantido até o fim do período;",
  "Em caso de falha no pagamento de uma parcela, o acesso ao plano é bloqueado imediatamente, sem período de graça, retornando automaticamente ao plano gratuito;",
  "Os meios de pagamento aceitos são PIX e cartão de crédito, processados via Mercado Pago;",
  "Campo de código promocional na tela de planos permite ativação de planos especiais via token.",
  "4.3 Direito de arrependimento (CDC, art. 49):",
  "O usuário tem direito a se arrepender da contratação de qualquer plano pago no prazo de 7 (sete) dias corridos, contados da data da assinatura, com direito a reembolso integral dos valores pagos, independentemente do motivo, conforme o Código de Defesa do Consumidor.",
  "A solicitação pode ser feita pelo app ou pelo canal contato@usepromofy.com;",
  "Após o decurso do prazo de 7 dias, aplicam-se as regras de cancelamento da Seção 4.2: o acesso permanece ativo até o fim do período contratado, mas não há reembolso de valores já pagos nem de parcelas vincendas.",
  "5. REGRAS DE USO DE CUPONS",
  "Os cupons possuem prazos de validade e condições específicas de uso que devem ser observadas pelo usuário;",
  "Ao ativar um cupom, é gerado automaticamente um código único (formato PRM-XXXXXX) com validade de 5 horas a partir da ativação;",
  "O usuário receberá notificação push 1 hora antes da expiração do código ativado;",
  "Após a exibição do código, o cancelamento do cupom não é mais permitido — medida de prevenção a fraudes;",
  "Cupons não utilizados dentro do prazo expiram automaticamente, sem direito a reembolso ou revalidação;",
  "O sistema bloqueia a reativação do mesmo cupom pelo mesmo usuário por 24 horas após cancelamento;",
  "O usuário que cancelar o mesmo cupom mais de 3 vezes no mesmo dia ficará bloqueado de ativar novos cupons por 24 horas;",
  "Quando o estabelecimento não confirmar o resgate antes da expiração do código, o cupom recebe o status 'Resgatado sem baixa', é contabilizado como consumido e não gera PromoPoints nem dispara NPS;",
  "Visibilidade de cupons para usuários do plano gratuito: apenas cupons cujo desconto seja igual ou superior ao preço vigente do plano Básico são visíveis para não assinantes — regra calculada dinamicamente pelo sistema.",
  "6. GAMIFICAÇÃO — PROMOPOINTS",
  "O sistema acumula PromoPoints automaticamente após resgate confirmado de cupom e resposta ao NPS;",
  "Cupons com status 'Resgatado sem baixa' não geram PromoPoints;",
  "O usuário participa de ranking mensal e pode trocar pontos por recompensas: cupons especiais, desconto em assinatura ou upgrade de plano;",
  "A Promofy se reserva o direito de alterar as regras do programa de pontos mediante comunicação prévia.",
  "7. SISTEMA DE INDICAÇÕES",
  "Cada usuário recebe um link exclusivo de indicação para compartilhamento;",
  "PromoPoints são concedidos ao indicador por cadastro e por assinatura do indicado;",
  "A Promofy pode suspender ou modificar o programa de indicações em caso de suspeita de fraude ou uso indevido;",
  "É vedada a criação de múltiplas contas para obtenção de vantagens indevidas.",
  "8. ATUALIZAÇÕES DO CATÁLOGO E VEDAÇÕES DE USO",
  "8.1 Atualizações da plataforma:",
  "O catálogo de estabelecimentos parceiros, cupons e promoções é atualizado regularmente e pode sofrer inclusões, alterações ou remoções a qualquer momento, por motivos operacionais, comerciais ou estratégicos, sem necessidade de aviso prévio individual;",
  "É de responsabilidade do usuário consultar regularmente o app para verificar a lista atualizada de parceiros, cupons disponíveis e suas condições de uso;",
  "A Promofy não se responsabiliza por divergências entre informações desatualizadas eventualmente retidas no dispositivo do usuário (cache) e a realidade vigente no momento da utilização.",
  "8.2 Vedações de uso da plataforma:",
  "É vedada a utilização da Promofy para fins de revenda, sublicenciamento ou exploração comercial dos cupons e benefícios oferecidos;",
  "É vedada a coleta de dados, listas de cupons, preços, estabelecimentos ou quaisquer informações da plataforma por meio de robôs, scrapers, crawlers ou quaisquer outras ferramentas automatizadas de extração de dados, sem autorização expressa e por escrito da Promofy;",
  "A violação desta cláusula sujeita o usuário ao bloqueio imediato da conta, sem prejuízo das medidas cíveis e criminais cabíveis.",
  "9. RESPONSABILIDADES DA PROMOFY",
  "Manter a plataforma ativa, segura e em conformidade com a legislação vigente;",
  "A Promofy NÃO é responsável pelos produtos, serviços, atendimento ou qualidade dos estabelecimentos parceiros;",
  "A Promofy não garante disponibilidade ininterrupta e não responde por falhas de terceiros, caso fortuito ou força maior;",
  "A Promofy não garante resultados financeiros, vantagens específicas ou economia direta decorrente do uso da plataforma.",
  "10. RESPONSABILIDADES DO USUÁRIO",
  "Utilizar a plataforma de forma lícita, respeitosa e em conformidade com estes Termos;",
  "É vedado: revender ou comercializar cupons; usar códigos promocionais de forma fraudulenta; burlar limitações de uso; realizar cadastros múltiplos para obter vantagens indevidas.",
  "11. PRIVACIDADE E PROTEÇÃO DE DADOS",
  "O tratamento de dados pessoais é regido pela Política de Privacidade da Promofy, disponível no app e no site, em conformidade com a LGPD (Lei nº 13.709/2018). Ao se cadastrar, o usuário consente com o tratamento descrito naquela política.",
  "12. ENCERRAMENTO DA CONTA",
  "O usuário pode solicitar a exclusão de sua conta a qualquer momento;",
  "O encerramento da conta não exime o usuário do pagamento das parcelas vincendas do plano anual contratado, ressalvado o direito de arrependimento previsto na Seção 4.3;",
  "A Promofy pode suspender ou excluir contas em casos de fraude, uso indevido ou descumprimento destes Termos;",
  "Dados serão tratados conforme a Política de Privacidade após o encerramento.",
  "13. LIMITAÇÃO DE RESPONSABILIDADE",
  "Em nenhuma hipótese a Promofy será responsável por danos indiretos, lucros cessantes ou prejuízos decorrentes da relação de consumo entre usuário e estabelecimento parceiro. A responsabilidade da Promofy limita-se à intermediação tecnológica entre as partes, conforme detalhado na Seção 2.",
  "14. ALTERAÇÕES NOS TERMOS",
  "A Promofy poderá atualizar estes Termos a qualquer tempo, com publicação da versão revisada no app e no site. Alterações relevantes serão comunicadas com antecedência mínima de 10 dias. O uso contínuo da plataforma após a alteração implica concordância com a nova versão.",
  "15. DISPOSIÇÕES GERAIS",
  "Foro competente: comarca de Palmas – Tocantins, com renúncia a qualquer outro;",
  "Lei aplicável: legislação brasileira, em especial o Código de Defesa do Consumidor (Lei 8.078/1990), o Código Civil, a LGPD e o Marco Civil da Internet (Lei 12.965/2014);",
  "A tolerância quanto ao descumprimento não configura novação ou renúncia de direitos;",
  "Canal de atendimento: contato@usepromofy.com."
];
